import type { Metadata } from "next";
import {
  BrainCircuit,
  Scale,
  ShieldCheck,
  Eye,
  BookCheck,
  HeartPulse,
  Zap,
  Database,
  Code2,
  Palette,
  Brain,
  Lock,
  Network,
} from "lucide-react";

import { Badge } from "@/components/ui/badge";

export const metadata: Metadata = {
  title: "About | Medipedia",
  description:
    "Learn how Medipedia builds trust in health knowledge through AI generation, council evaluation, and transparent scoring.",
};

export default function AboutPage() {
  return (
    <div className="max-w-6xl mx-auto px-6 py-10">
      {/* ── Section 1: Hero ─────────────────────────────── */}
      <section className="relative overflow-hidden rounded-3xl border bg-card p-10 md:p-16">
        {/* Animated gradient blobs */}
        <div className="pointer-events-none absolute -top-24 -right-24 h-96 w-96 rounded-full bg-teal-500/20 blur-3xl animate-pulse-slow" />
        <div className="pointer-events-none absolute -bottom-24 -left-24 h-96 w-96 rounded-full bg-amber-500/20 blur-3xl animate-pulse-slow" />

        <div className="relative">
          <p className="text-xs uppercase tracking-[0.25em] text-teal-500">
            About Medipedia
          </p>
          <h1 className="mt-4 text-5xl md:text-7xl font-semibold leading-tight tracking-tight">
            Health knowledge{" "}
            <span className="bg-gradient-to-r from-teal-400 to-amber-400 bg-clip-text text-transparent">
              you can trust.
            </span>
          </h1>
          <p className="mt-6 max-w-2xl text-lg text-muted-foreground">
            Medipedia is a safety-first health encyclopedia where every article
            is generated by Lumi, our AI research agent, then evaluated by an
            independent council of specialist judges before it ever reaches you.
          </p>
        </div>
      </section>

      {/* ── Section 2: The Problem ──────────────────────── */}
      <section className="mt-20">
        <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">
          Why this matters
        </p>
        <h2 className="mt-3 text-4xl font-semibold tracking-tight">
          Health misinformation is everywhere.
        </h2>
        <p className="mt-4 max-w-2xl text-muted-foreground">
          Unverified health content spreads faster than facts. Medipedia exists
          to change that with structured, transparent, and repeatable quality
          assurance.
        </p>

        <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          {[
            { stat: "3", label: "Independent judges per article" },
            { stat: "A/B/C", label: "Citation source tiers" },
            { stat: "24h", label: "Automatic re-review cycle" },
            { stat: "100", label: "Maximum trust score" },
          ].map((item) => (
            <div
              key={item.stat}
              className="glass-strong rounded-2xl p-6 text-center transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
            >
              <p className="text-3xl font-bold tracking-tight">{item.stat}</p>
              <p className="mt-2 text-sm text-muted-foreground">
                {item.label}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Section 3: How It Works ─────────────────────── */}
      <section className="mt-20">
        <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">
          The pipeline
        </p>
        <h2 className="mt-3 text-4xl font-semibold tracking-tight">
          From topic to trusted article.
        </h2>

        <div className="mt-10 grid gap-6 md:grid-cols-3">
          {/* Step 01 */}
          <div className="glass-strong rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-500/10">
                <BrainCircuit className="h-5 w-5 text-teal-500" />
              </div>
              <span className="text-xs font-medium text-muted-foreground">
                Step 01
              </span>
            </div>
            <h3 className="mt-4 text-lg font-semibold text-teal-500">
              Lumi Generates
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Our AI research agent drafts a comprehensive, citation-backed
              article from trusted medical sources, structuring content with
              clear sections and evidence tiers.
            </p>
          </div>

          {/* Step 02 */}
          <div className="glass-strong rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/10">
                <Scale className="h-5 w-5 text-amber-500" />
              </div>
              <span className="text-xs font-medium text-muted-foreground">
                Step 02
              </span>
            </div>
            <h3 className="mt-4 text-lg font-semibold text-amber-500">
              Council Evaluates
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Three independent judges -- Clarity, Evidence, and Safety --
              evaluate every article against strict rubrics, producing verdicts
              and detailed feedback.
            </p>
          </div>

          {/* Step 03 */}
          <div className="glass-strong rounded-2xl p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10">
                <ShieldCheck className="h-5 w-5 text-emerald-500" />
              </div>
              <span className="text-xs font-medium text-muted-foreground">
                Step 03
              </span>
            </div>
            <h3 className="mt-4 text-lg font-semibold text-emerald-500">
              Trust Is Earned
            </h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Scores combine into a transparent trust scorecard. Articles are
              published only when they meet the quality threshold, and are
              automatically re-reviewed on a 24-hour cycle.
            </p>
          </div>
        </div>
      </section>

      {/* ── Section 4: The Council ──────────────────────── */}
      <section className="mt-20">
        <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">
          Quality assurance
        </p>
        <h2 className="mt-3 text-4xl font-semibold tracking-tight">
          Three judges. One verdict.
        </h2>
        <p className="mt-4 max-w-2xl text-muted-foreground">
          Every article passes through our council of specialist AI judges.
          Each evaluates a different dimension of quality.
        </p>

        <div className="mt-10 grid gap-6 md:grid-cols-3">
          {/* Clarity */}
          <div className="rounded-2xl border-2 border-teal-500/30 bg-teal-500/5 p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
            <div className="flex items-center justify-between">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-500/10">
                <Eye className="h-5 w-5 text-teal-500" />
              </div>
              <Badge variant="success">PASS</Badge>
            </div>
            <h3 className="mt-4 text-lg font-semibold">Clarity</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Evaluates readability, structure, and plain-language
              accessibility. Ensures content is understandable by a general
              audience without sacrificing accuracy.
            </p>
          </div>

          {/* Evidence */}
          <div className="rounded-2xl border-2 border-amber-500/30 bg-amber-500/5 p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
            <div className="flex items-center justify-between">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/10">
                <BookCheck className="h-5 w-5 text-amber-500" />
              </div>
              <Badge variant="warning">WARN</Badge>
            </div>
            <h3 className="mt-4 text-lg font-semibold">Evidence</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Checks citation quality, source tiers, and factual grounding.
              Every claim must trace back to a reputable medical source with a
              clear evidence tier.
            </p>
          </div>

          {/* Safety */}
          <div className="rounded-2xl border-2 border-emerald-500/30 bg-emerald-500/5 p-6 transition-all duration-300 hover:-translate-y-1 hover:shadow-xl">
            <div className="flex items-center justify-between">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10">
                <HeartPulse className="h-5 w-5 text-emerald-500" />
              </div>
              <Badge variant="success">PASS</Badge>
            </div>
            <h3 className="mt-4 text-lg font-semibold">Safety</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Guards against harmful advice, dangerous omissions, and
              misleading claims. Flags content that could lead to patient harm
              if taken at face value.
            </p>
          </div>
        </div>
      </section>

      {/* ── Section 5: Built With ───────────────────────── */}
      <section className="mt-16">
        <p className="text-xs uppercase tracking-[0.25em] text-muted-foreground">
          Technology
        </p>
        <h2 className="mt-3 text-4xl font-semibold tracking-tight">
          Built with modern tools.
        </h2>
        <p className="mt-4 max-w-2xl text-muted-foreground">
          Medipedia is built on a modern, type-safe stack designed for
          reliability, performance, and developer experience.
        </p>

        <div className="mt-10 flex flex-wrap gap-3">
          {[
            { icon: Zap, label: "Next.js 16" },
            { icon: Code2, label: "React 19" },
            { icon: Code2, label: "TypeScript" },
            { icon: Palette, label: "Tailwind CSS" },
            { icon: Database, label: "Prisma + PostgreSQL" },
            { icon: Brain, label: "Google Gemini" },
            { icon: Lock, label: "NextAuth.js" },
            { icon: Network, label: "D3.js" },
          ].map((tech) => (
            <div
              key={tech.label}
              className="glass inline-flex items-center gap-2 rounded-full px-4 py-2 text-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
            >
              <tech.icon className="h-4 w-4 text-muted-foreground" />
              {tech.label}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
